#!/bin/bash

get_host_status() {
	host_status=$(/usr/sbin/ampere_power_util.sh status)

	if [ "$host_status" = "gpioget failed" ]; then
		echo "Failed to get host status"
		exit 1
	fi
}

set_gpio() {
	gpio=$(gpiofind "$1")
	gpioset "${gpio}"="$2"
}

add_sel() {
	MESSAGE="$1"
	LEVEL_STR="$2"
	LEVEL_ENUM="xyz.openbmc_project.Logging.Entry.Level.Error"

	case "$LEVEL_STR" in
		"Error")
			LEVEL_ENUM="xyz.openbmc_project.Logging.Entry.Level.Error"
			;;
		"Info")
			LEVEL_ENUM="xyz.openbmc_project.Logging.Entry.Level.Informational"
		;;
		*)
			echo "Unknown log level: $LEVEL_STR"
			;;
	esac

	busctl call \
		xyz.openbmc_project.Logging /xyz/openbmc_project/logging \
		xyz.openbmc_project.Logging.Create Create "ssa{ss}" \
		"$MESSAGE" "$LEVEL_ENUM" 0
}
