#!/bin/bash
# Handle host power state for chassis poweron failure.

# shellcheck source=meta-asrock/meta-ampere/meta-common/recipes-phosphor/state/phosphor-state-manager/ampere-state-helpers
source /usr/libexec/phosphor-state-manager/ampere-state-helpers

get_host_status

if [ "$host_status" != "on" ]
then
    # Stop obmc-host-startmin@{}.target to avoid chassis-state-manager to set power state to On.
    /bin/systemctl stop obmc-host-startmin@0.target

    # Set host power state to Off.
    /bin/sh -c "busctl set-property $(mapper get-service /xyz/openbmc_project/state/host0) \
        /xyz/openbmc_project/state/host0 \
        xyz.openbmc_project.State.Host CurrentHostState \
        s xyz.openbmc_project.State.Host.HostState.Off"
fi
