#Host console log

module(load="imuxsock" SysSock.Use="off")

template(name="ConsoleTemplate" type="string" string="%rawmsg%")

ruleset(name="ConsoleCPURuleset") {
  action(type="omfile" file="/var/log/obmc-console-cpu.log" template="ConsoleTemplate")
}
ruleset(name="ConsoleTFARuleset") {
  action(type="omfile" file="/var/log/obmc-console-tfa.log" template="ConsoleTemplate")
}
ruleset(name="ConsoleSECPRORuleset") {
  action(type="omfile" file="/var/log/obmc-console-secpro.log" template="ConsoleTemplate")
}
ruleset(name="ConsoleMPRORuleset") {
  action(type="omfile" file="/var/log/obmc-console-mpro.log" template="ConsoleTemplate")
}

# Custom socket for serial console logs.
input(type="imuxsock"
  Socket="/run/rsyslog/console/cpu"
  CreatePath="on"
  UseSpecialParser="off"
  ParseHostname="off"
  ruleset="ConsoleCPURuleset")

input(type="imuxsock"
  Socket="/run/rsyslog/console/tfa"
  CreatePath="on"
  UseSpecialParser="off"
  ParseHostname="off"
  ruleset="ConsoleTFARuleset")

input(type="imuxsock"
  Socket="/run/rsyslog/console/secpro"
  CreatePath="on"
  UseSpecialParser="off"
  ParseHostname="off"
  ruleset="ConsoleSECPRORuleset")

input(type="imuxsock"
  Socket="/run/rsyslog/console/mpro"
  CreatePath="on"
  UseSpecialParser="off"
  ParseHostname="off"
  ruleset="ConsoleMPRORuleset")

input(type="imuxsock"
  Socket="/run/rsyslog/console/scp"
  CreatePath="on"
  UseSpecialParser="off"
  ParseHostname="off"
  ruleset="ConsoleSCPRuleset")

$EscapeControlCharactersOnReceive off
$DropTrailingLFOnReception off

